### ISSUE TITLE
Test transitions on IE6

### ISSUE THREAD

**Issue by JLeuze** [JLeuze/Meteor-Slides#49]
Slideshow cycles but slides aren't fading, look into that and test other transitions.

**Comment by Squazz** [comment]
Is this still a problem? IE6 & 7 really aren't used anymore. We are <1% with each. So <2% on both combined. 

IE6: https://www.modern.ie/en-us/ie6countdown
IE7: http://www.theie7countdown.com/

**Comment by JLeuze** [comment]
No, it's not. I'm only concerned about IE8+, the latest versions of Chrome, Firefox, Safari, Android, and iOS. That seems like enough!
